CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
        CONSTRAINT pk_user PRIMARY KEY(id),
        CONSTRAINT UQ_USER_EMAIL UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(1000) NOT NULL,
    requestor BIGINT NOT NULL,
    created TIMESTAMP NOT NULL,
        CONSTRAINT pk_request PRIMARY KEY(id),
        CONSTRAINT fk_requests_to_users FOREIGN KEY(requestor) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    available BOOLEAN,
    owner BIGINT NOT NULL,
    request BIGINT,
        CONSTRAINT pk_item PRIMARY KEY(id),
        CONSTRAINT fk_items_to_users FOREIGN KEY(owner) REFERENCES users(id),
        CONSTRAINT fk_items_to_requests FOREIGN KEY(request) REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS booking
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start TIMESTAMP,
    end TIMESTAMP,
    item BIGINT NOT NULL,
    booker BIGINT NOT NULL,
    status VARCHAR(50),
        CONSTRAINT pk_booking PRIMARY KEY(id),
        CONSTRAINT fk_booking_to_items FOREIGN KEY(item) REFERENCES items(id),
        CONSTRAINT fk_booking_to_users FOREIGN KEY(booker) REFERENCES users(id)
);



